name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      firmware_branch:
        description: "Branch or tag to checkout from meshtastic/firmware"
        required: true
        type: string
        default: "develop"
      variant:
        description: "Variant to build (e.g., cutretech-esp32s3)"
        required: true
        type: string
      modify_mqtt_line:
        description: "mqqt me bro"
        required: true
        type: boolean
        default: false

run-name: Build ${{ inputs.variant }}-${{ inputs.firmware_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIRMWARE_ARCHIVE: firmware-${{ inputs.variant }}-${{ inputs.firmware_branch }}.tar.xz

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5
        with:
          path: builder

      - name: Checkout meshtastic/firmware
        uses: actions/checkout@v5
        with:
          repository: meshtastic/firmware
          ref: ${{ inputs.firmware_branch }}
          path: firmware
          submodules: recursive

      - name: Copy variants folder
        run: cp -r builder/variants/* firmware/variants/

      - name: Copy boards folder
        run: cp -r builder/boards/* firmware/boards/

      - name: Modify MQTT.cpp line (optional)
        if: inputs.modify_mqtt_line == true
        working-directory: firmware
        run: |
          sed -i 's#bool dontUplink = !mp_decoded.decoded.has_bitfield || !(mp_decoded.decoded.bitfield & BITFIELD_OK_TO_MQTT_MASK);#bool dontUplink = false;#' src/mqtt/MQTT.cpp

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pip install "scons==4.7.0"
        

      - name: Build firmware
        working-directory: firmware
        run:  pio run -e ${{ inputs.variant }} --disable-auto-clean


      - name: Create firmware archive
        run: |
          cd firmware/.pio/build/${{ inputs.variant }}
          tar -cJf ${{ env.FIRMWARE_ARCHIVE }} --ignore-failed-read *.bin *.uf2

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.FIRMWARE_ARCHIVE }}
          path: firmware/.pio/build/${{ inputs.variant }}/${{ env.FIRMWARE_ARCHIVE }}
          archive: false
          if-no-files-found: error
